-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        -- avoid starting multiple hyprlock instances.
        --    before_sleep_cmd = loginctl lock-session    # lock before suspend.
        inhibit_sleep = 0,
        after_sleep_cmd = "wlopm --on '*'",
        -- to avoid having to press a key twice to turn on the display.
    },
})

hl.config({
    listener = {
        timeout = 150,
        -- 2.5min.
        on_timeout = "brightnessctl -s set 10",
        -- set monitor backlight to minimum, avoid 0 on OLED monitor.
        on_resume = "brightnessctl -r",
        -- monitor backlight restore.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

--listener {

--    timeout = 300                                 # 5min

--    on-timeout = loginctl lock-session            # lock screen when timeout has passed

--}

hl.config({
    listener = {
        timeout = 600,
        -- 10min
        on_timeout = "wlopm --off '*'",
        -- screen off when timeout has passed
        on_resume = "wlopm --on '*'",
        -- screen on when activity is detected after timeout has fired.
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

--listener {

--    timeout = 1800                                # 30min

--    on-timeout = systemctl suspend                # suspend pc

--}
